### ISSUE TITLE
OfCloudFileByLine issue

### ISSUE THREAD

**Issue by eiriktsarpalis** [mbraceproject/MBrace.Core#156]
There seems to be a problem with the implementation of `Of*ByLine` as of late. Here's an error found by one of the existing unit tests:
```
MBrace.Runtime.Tests.InMemory CloudFlow tests.CloudFlow tests.2. CloudFlow : OfCloudFileByLine:
System.Exception : Falsifiable, after 9 tests (1 shrink) (StdGen (134548942,296096179)):
Original:
([|"O"|], N)
Shrunk:
([|"a"|], N)
with exception:
NUnit.Framework.AssertionException:   Expected is <System.String[1]>, actual is <System.String[0]>
  Values differ at index [0]
  Missing:  < "a" >
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at <StartupCode$MBrace-Core-Tests>.$CloudFlowTests.f@297-22.Invoke(Tuple`2 tupledArg) in C:\Users\eirik\Development\mbrace\MBrace.Core\tests\MBrace.Core.Tests\CloudFlowTests.fs:line 320
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Testable.fs:line 161
```
Note that I had to run that specific test 2 or 3 times before FsCheck could come across the counterexample.

**Comment by palladin** [comment]
Fixed in https://github.com/mbraceproject/MBrace.Core/commit/675e1c9745c5594df322882fd890c1171587534f
