### ISSUE TITLE
SerializationException on DataContracts

### ISSUE THREAD

**Issue by petarvucetin** [mbraceproject/MBrace.Core#164]
Is there a reason that DataContract annotated types are not serializible? 

```
INFO : Uploading 'FSI-ASSEMBLY_b97c3b7e-014a-4dff-b7b7-267cf5b19f05_4, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' [IMG 4.50 KiB]
System.Runtime.Serialization.SerializationException: Cloud process returns non-serializable type 'CRM.Contracts.Account []'.
   at MBrace.Runtime.Combinators.runStartAsCloudProcess@297.Invoke(Unit unitVar) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Runtime\Combinators.fs:line 298
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
   at MBrace.Core.Internals.AsyncExtensions.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\AsyncExtensions.fs:line 101
   at <StartupCode$FSI_0016>.$FSI_0016.main@() in D:\Development\jams-data-migration\f#\src\BootstrapLoader\Script.fsx:line 52
Stopped due to error

```
Contract definition:

```
[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("account")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.0000.2074")]
	public partial class Account : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
```

**Comment by eiriktsarpalis** [comment]
Data contract serialization is supported in principle, but there might be a bug in implementation. Could you please provide the full implementation of the Account class?

**Comment by petarvucetin** [comment]
The class is VERY large. 
[Account.zip](https://github.com/mbraceproject/MBrace.Core/files/217504/Account.zip)

**Comment by eiriktsarpalis** [comment]
My hunch here is that the problem arises from the fact that the base class (`Microsoft.Xrm.Sdk.Entity`) is not serializable. From the F# repl that runs mbrace, could you please try running the following code and report back with the output?
```fsharp
Nessos.FsPickler.FsPickler.GeneratePickler<Account>()
```

**Comment by eiriktsarpalis** [comment]
Also, could you please try serializing your account instance using `NetDataContractSerializer` to verify that it works there?

**Comment by petarvucetin** [comment]
[Entity](https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.entity.aspx?f=255&MSPPError=-2147217396)  class is coming from MS. I will test the serialization in a minute

**Comment by eiriktsarpalis** [comment]
If this is an ORM entity, I would expect it to not support serialization by design. The way to go here would be to copy the data over to a handmade POCO for communication purposes.

**Comment by petarvucetin** [comment]
Looks like it does not like [AttributeCollection](https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.attributecollection.aspx).
```
Nessos.FsPickler.NonSerializableTypeException: Type 'CRM.Contracts.Account' contains non-serializable field of type 'Microsoft.Xrm.Sdk.AttributeCollection'.
   at Nessos.FsPickler.Utils.Exn`1.get_Value() in C:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Utils\Utils.fs:line 53
   at Nessos.FsPickler.PicklerCache.Nessos-FsPickler-IPicklerResolver-Resolve[T]() in C:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\PicklerGeneration\PicklerCache.fs:line 82
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in D:\Development\f#\src\BootstrapLoader\Script.fsx:line 24
```

**Comment by petarvucetin** [comment]
These classes are used by WCF communication with CRM so I am positive that they are all serializible.

**Comment by palladin** [comment]
One interesting observation is that AttributeCollection is not decorated with a "serializable" attribute but its superclass DataCollection has [SerializableAttribute]
https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.attributecollection.aspx
https://msdn.microsoft.com/en-us/library/gg308363.aspx

**Comment by eiriktsarpalis** [comment]
Btw, can you confirm that this works with NetDataContractSerializer?

**Comment by petarvucetin** [comment]
I can confirm that it works. NetDC is the default serializer for WCF for intranet bindings.

```
let a = CRM.Contracts.Account()
a.AccountNumber <- "123"

let ms = new MemoryStream()        
let s = NetDataContractSerializer()
s.Serialize(ms, a)
ms.Position <- 0L
let o = s.Deserialize(ms) :?>  CRM.Contracts.Account
printfn "AccountNumber is %s" o.AccountNumber

--output

AccountNumber is 123

val a : CRM.Contracts.Account
val ms : MemoryStream
val s : NetDataContractSerializer
val o : CRM.Contracts.Account
val it : unit = ()

> 

```

**Comment by petarvucetin** [comment]
My guess is that I am missing a references to a DLL where something is defined that is used in the Account class. I will continue to test but please make this non-issue for now.

**Comment by petarvucetin** [comment]
I have a slight variation on this problem

```
INFO : Uploading data dependency 'MBrace.Core.Cloud`1[MBrace.Flow.PersistedCloudFlow`1[System.Tuple`2[System.Object,JAMS.CRM.Contracts.Account]]] x@1-1' [4.81 KiB]
INFO : Uploading data dependency 'MBrace.Flow.CloudFlow`1[System.Tuple`2[System.Object,JAMS.CRM.Contracts.Account]] flow@1' [4.68 KiB]


Nessos.FsPickler.NonSerializableTypeException: Type 'System.Tuple`2[System.Object,CRM.Contracts.Account]' contains non-serializable field of type 'CRM.Contracts.Account'.

```

**Comment by eiriktsarpalis** [comment]
Here's a temporary workaround. At the top of your application add the following line:
```fsharp
Nessos.FsPickler.FsPickler.DeclareSerializable<Microsoft.Xrm.Sdk.AttributeCollection>()
```
This will tell FsPickler to treat the type as if it carried the `Serializable` attribute.

**Comment by petarvucetin** [comment]
That did not help. I must be doing something wrong...

This is what I am doing

```
Nessos.FsPickler.FsPickler.DeclareSerializable<Microsoft.Xrm.Sdk.AttributeCollection>()

let cluster = Config.GetCluster() 

type command = SqlCommandProvider<query , cns>

let memberAccountBuilder (row: command.Record) = 
    let entity  = CRM.Contracts.Account()
    entity.smw104_AccountType  <- OptionSetValue((int) smw104_accounttype.Member)
    entity.AccountNumber <- row.AccountNumber.ToString()
    entity.Name <- row.AccountNumber.ToString()
    printfn "processed account # %s \n" (entity.AccountNumber.ToString())
    (row,entity)

let sqlCall = 
    use cmd = new command()
    cmd.Execute()

let memberQuery = 
    sqlCall
      |> Seq.toArray
      |> CloudFlow.OfArray
      |> CloudFlow.map memberAccountBuilder
      |> CloudFlow.persist StorageLevel.Memory
      |> cluster.Run
      
------------
OUTPUT
--------


val cluster : MBrace.Thespian.ThespianCluster
val orgService : Xrm.Client.Services.OrganizationService
type command = FSharp.Data.SqlCommandProvider<...>
val memberAccountBuilder :
  row:FSharp.Data.SqlCommandProvider<...>.Record ->
    FSharp.Data.SqlCommandProvider<...>.Record * CRM.Contracts.Account
val sqlCall :
  System.Collections.Generic.IEnumerable<FSharp.Data.SqlCommandProvider<...>.Record>

> 
Binding session to 'D:\Development\f#\src\BootstrapLoader\../packages/Streams/lib/net45\Streams.dll'...
Binding session to 'D:\CRM\SDK\Bin\Microsoft.Xrm.Sdk.Deployment.dll'...
Binding session to 'D:\Development\f#\src\BootstrapLoader\..\packages\Dynamics.Crm.Sdk.Clean\lib\Microsoft.Xrm.Sdk.dll'...
INFO : Uploading 'System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 410.23 KiB]
INFO : Uploading 'Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 1.10 MiB]
INFO : Uploading 'MBrace.Flow, Version=1.1.6.0, Culture=neutral, PublicKeyToken=null' [IMG 384.50 KiB, PDB 0.53 MiB]
INFO : Uploading 'System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 1.45 MiB]
INFO : Uploading 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 195.68 KiB]
INFO : Uploading 'Microsoft.Xrm.Sdk, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 485.72 KiB]
INFO : Uploading 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 0.57 MiB]
INFO : Uploading 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 1.76 MiB]
INFO : Uploading 'System.ServiceModel.Internals, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 244.27 KiB]
INFO : Uploading 'System.Printing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 358.34 KiB]
INFO : Uploading 'System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 242.64 KiB]
INFO : Uploading 'System.Drawing.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 110.22 KiB]
INFO : Uploading 'Microsoft.VisualBasic.Activities.Compiler, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 3.05 MiB]
INFO : Uploading 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 0.62 MiB]
INFO : Uploading 'System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 0.81 MiB]
INFO : Uploading 'ReachFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 0.56 MiB]
INFO : Uploading 'Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 35.09 KiB]
INFO : Uploading 'FSI-ASSEMBLY_5318f426-28c4-40d5-b121-ba48ece9c9c3_1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' [IMG 72.50 KiB]
INFO : Uploading 'System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 105.16 KiB]
INFO : Uploading 'System.Runtime.Serialization.Formatters.Soap, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 138.77 KiB]
INFO : Uploading 'Microsoft.Xrm.Client, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 284.17 KiB]
INFO : Uploading 'PresentationUI, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 0.81 MiB]
INFO : Uploading 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 5.80 MiB]
INFO : Uploading 'CRM.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0a2a0089dfd19253' [IMG 5.17 MiB, PDB 14.19 MiB]
INFO : Uploading 'System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 197.24 KiB]
INFO : Uploading 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 3.33 MiB]
INFO : Uploading 'System.Xaml.Hosting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 41.62 KiB]
INFO : Uploading 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 122.81 KiB]
INFO : Uploading 'UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 48.13 KiB]
INFO : Uploading 'System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 319.73 KiB]
INFO : Uploading 'Microsoft.IdentityModel, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 1.04 MiB]
INFO : Uploading 'System.ServiceModel.Channels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 153.24 KiB]
INFO : Uploading 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 1.20 MiB]
INFO : Uploading 'System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 0.80 MiB]
INFO : Uploading 'System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 4.77 MiB]
INFO : Uploading 'UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 103.35 KiB]
INFO : Uploading 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 99.14 KiB]
INFO : Uploading 'System.DirectoryServices.Protocols, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 195.79 KiB]
INFO : Uploading 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 5.10 MiB]
INFO : Uploading 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 267.16 KiB]
INFO : Uploading 'Microsoft.Xrm.Sdk.Deployment, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 95.71 KiB]
INFO : Uploading 'Microsoft.SqlServer.TransactSql.ScriptDom, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' [IMG 2.75 MiB]
INFO : Uploading 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [IMG 131.22 KiB]
INFO : Uploading 'System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 69.27 KiB]
INFO : Uploading 'System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 0.53 MiB]
INFO : Uploading 'Streams, Version=0.4.1.0, Culture=neutral, PublicKeyToken=null' [IMG 338.00 KiB, PDB 421.50 KiB]
INFO : Uploading 'FSharp.Data.SqlClient, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null' [IMG 0.51 MiB, PDB 0.67 MiB]
INFO : Uploading 'System.Runtime.DurableInstancing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 169.20 KiB]
INFO : Uploading 'System.Activities.DurableInstancing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [IMG 140.71 KiB]
INFO : Uploading data dependency 'MBrace.Flow.CloudFlow`1[System.Tuple`2[System.Object,CRM.Contracts.Account]] flow@1' [4.67 KiB]
INFO : Uploading data dependency 'MBrace.Core.Cloud`1[MBrace.Flow.PersistedCloudFlow`1[System.Tuple`2[System.Object,CRM.Contracts.Account]]] x@1-1' [4.82 KiB]
INFO : Uploading data dependency 'System.Object[] x@1-2' [4.42 KiB]
WARNING : Could not serialize data dependencies: Microsoft.FSharp.Core.FSharpOption`1[MBrace.Thespian.ThespianCluster] thespian@, MBrace.Thespian.ThespianCluster cluster@, Microsoft.Xrm.Client.Services.OrganizationService orgService@, System.Collections.Generic.IEnumerable`1[System.Object] sqlCall@, FSharp.Data.ISqlCommand Implementation cmd@49
INFO : Posted CloudProcess<PersistedCloudFlow<(obj * CRM.Contracts.Account)>> 'd60d9f09-f528-4430-9be8-744bf4240ae6'.
Nessos.FsPickler.NonSerializableTypeException: Type 'System.Tuple`2[System.Object,CRM.Contracts.Account]' contains non-serializable field of type 'CRM.Contracts.Account'.
   at Nessos.FsPickler.Utils.Exn`1.get_Value() in C:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Utils\Utils.fs:line 53
   at Nessos.FsPickler.PicklerCache.Nessos-FsPickler-IPicklerResolver-Resolve[T]() in C:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\PicklerGeneration\PicklerCache.fs:line 82
>    at MBrace.Runtime.Utils.FsPicklerExtensions.FsPickler-PartitionSequenceBySize-Static@78-1.Invoke(Unit unitVar) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Utils\Serialization.fs:line 78
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
   at Cloud.Parallel(seq<Cloud<PersistedCloudFlow`1> * IWorkerRef> computations)
--- End of stack trace from previous location where exception was thrown ---
   at <StartupCode$MBrace-Runtime>.$CloudProcess.AwaitResult@211-2.Invoke(CloudProcessResult _arg2) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Runtime\CloudProcess.fs:line 211
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)
   at MBrace.Core.Internals.AsyncExtensions.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\AsyncExtensions.fs:line 101
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in D:\Development\f#\src\BootstrapLoader\Script.fsx:line 52
Stopped due to error

      
      
```

**Comment by eiriktsarpalis** [comment]
It could be the case that `Account` contains other fields also not serializable, which like `AttributeCollection` might need to be flagged as such. Please run `FsPickler.GeneratePickler` as before to detect what those might be. In any case I'm working on a fix of this issue.

**Comment by petarvucetin** [comment]
Here is what I needed to declare for GeneratePickler to work.
```
Nessos.FsPickler.FsPickler.DeclareSerializable<Microsoft.Xrm.Sdk.AttributeCollection>()
Nessos.FsPickler.FsPickler.DeclareSerializable<Microsoft.Xrm.Sdk.FormattedValueCollection>()
Nessos.FsPickler.FsPickler.DeclareSerializable<Microsoft.Xrm.Sdk.RelatedEntityCollection>()
Nessos.FsPickler.FsPickler.GeneratePickler<CRM.Contracts.Account>()
```
But still have same outcome

```
Nessos.FsPickler.NonSerializableTypeException: Type 'System.Tuple`2[System.Object,CRM.Contracts.Account]' contains non-serializable field of type 'CRM.Contracts.Account'.
>    at Nessos.FsPickler.Utils.Exn`1.get_Value() in C:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Utils\Utils.fs:line 53
   at Nessos.FsPickler.PicklerCache.Nessos-FsPickler-IPicklerResolver-Resolve[T]() in C:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\PicklerGeneration\PicklerCache.fs:line 82
   at MBrace.Runtime.Utils.FsPicklerExtensions.FsPickler-PartitionSequenceBySize-Static@78-1.Invoke(Unit unitVar) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Utils\Serialization.fs:line 78
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
   at Cloud.Parallel(seq<Cloud<PersistedCloudFlow`1> * IWorkerRef> computations)
--- End of stack trace from previous location where exception was thrown ---
   at <StartupCode$MBrace-Runtime>.$CloudProcess.AwaitResult@211-2.Invoke(CloudProcessResult _arg2) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Runtime\CloudProcess.fs:line 211
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)
   at MBrace.Core.Internals.AsyncExtensions.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\AsyncExtensions.fs:line 101
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in D:\Development\f#\src\BootstrapLoader\Script.fsx:line 52
Stopped due to error

```

**Comment by eiriktsarpalis** [comment]
What stacktrace does `Nessos.FsPickler.FsPickler.GeneratePickler<CRM.Contracts.Account>()` generate?

**Comment by petarvucetin** [comment]
```
val it : Nessos.FsPickler.Pickler<CRM.Contracts.Account> =
  Nessos.FsPickler.CompositePickler`1[CRM.Contracts.Account]
    {ImplementationType = JAMS.CRM.Contracts.Account;
     IsCacheByRef = true;
     IsCloneableOnly = false;
     IsOfFixedSize = false;
     IsRecursiveType = true;
     Kind = NonSealed;
     PicklerInfo = DataContract;
     Type = CRM.Contracts.Account;
     UseWithSubtypes = false;}
> 
```

**Comment by petarvucetin** [comment]
Is it possible to set different serializer for Thespian or Azure?

**Comment by eiriktsarpalis** [comment]
I've updated the nuget packages. Could you try it out again?

**Comment by petarvucetin** [comment]
Fixed!

**Comment by eiriktsarpalis** [comment]
Nice! :+1:
